### ISSUE TITLE
Add missing Portal in Tooltip example

### ISSUE THREAD

**Issue by ceopaludetto** [chakra-ui/ark#1173]
### Description

Tooltip examples in documentation doesn't have Portal component around Positioner, this leads to incorrect rendering when people use `position: relative` or custom `z-index`.

### Proposed Solution or API

Add `<Portal />` component around `<TooltipPositioner />` like the example below:

```tsx
<Tooltip>
  <TooltipTrigger>
    <span>hover me</span>
  </TooltipTrigger>
 
  <Portal>
    <TooltipPositioner>
      <TooltipArrow>
        <TooltipInnerArrow />
      </TooltipArrow>
 
      <TooltipContent>My tooltip content</TooltipContent>
    </TooltipPositioner>
  </Portal>
</Tooltip>
```

### Additional Information

I've tested on a real implementation of the tooltip component and worked out of the box.

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. The docs have been updated and support for animation has been added.

Checkout the updated docs: https://ark-ui.com/docs/react/components/tooltip

**Comment by darrenbridenbeck-measurabl** [comment]
@cschroeter can you confirm if portaling tooltips is still possible? I'm not seeing it in the docs.

**Comment by cschroeter** [comment]
Sure you can portal all disclosure components. If this does not work please feel free to raise an issue.

**Comment by darrenbridenbeck-measurabl** [comment]
Thanks for the point in the right direction! I got confused because some components ([like popover](https://ark-ui.com/react/docs/components/popover#using-a-portal)) explicitly describe portalling, but tooltip does not. If it would be helpful, I'd be happy to put up a PR to expand the tooltip docs to cover using a portal. If not, no worries. Either way, thanks for the help!
