### ISSUE TITLE
ValueChangeDetails Event Type not Exported

### ISSUE THREAD

**Issue by elson-currentcorp** [chakra-ui/ark#1934]
### Description

I want to pass in a useCallback function into the onValueChange parameter of a Segment Group component:

```
const onValueChange = useCallback(
	(e: ValueChangeDetails) => {
		console.log(e.value);
	},
	[]
);

...

return (
	<CustomRadio onValueChange={onValueChange}/>
)
```

Typescript requires the `e` parameter variable to be typed.

![image](https://github.com/chakra-ui/ark/assets/148154522/13e77d3a-a1ac-4f68-a220-0143de9c8d74)

This throws a not exported error:

![image](https://github.com/chakra-ui/ark/assets/148154522/54c5ad2b-0008-459c-aca4-c4af3f4f8dcb)

### Link to Reproduction (or Detailed Explanation)

React with create react app

### Steps to Reproduce

Write the following line of code:

`import { ValueChangeDetails } from '@ark-ui/react';`

### Ark UI Version

1.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

N/A

**Comment by TylerAPfledderer** [comment]
Hey @elson-currentcorp !

On initial pass, it appears we do not have any event types like this exported for any component.

@cschroeter was there a blocker pulling these kinds of types in from Zag, or was this still in the queue to be addressed?

**Comment by cschroeter** [comment]
@TylerAPfledderer @elson-currentcorp 

I believe that Zag.js already export those types. The problem is that they can differ from machine to machine.
For example in the SegmentGroup the `ValueChangeDetails` are typed as:

```tsx
export interface ValueChangeDetails {
  value: string
}
```

while in the Accordion they are typed as 

```tsx
export interface ValueChangeDetails {
  value: string[]
}
```

To avoid naming conflicts we would re-write this to something like `AccordionValueChangeDetails`, `SegmentGroupChangeDetails` etc which is quite some effort. For now I would recommend to handle this in userland

```tsx
export const Basic = () => {
  const frameworks = ['React', 'Solid', 'Svelte', 'Vue']

  type ValueChangeDetails = {
    value: string
  }

  const handleValueChange = (e: ValueChangeDetails) => {
    console.log(e.value)
  }

  return (
    <SegmentGroup.Root onValueChange={handleValueChange}>
      <SegmentGroup.Indicator />
      {frameworks.map((framework) => (
        <SegmentGroup.Item key={framework} value={framework}>
          <SegmentGroup.ItemText>{framework}</SegmentGroup.ItemText>
          <SegmentGroup.ItemControl />
        </SegmentGroup.Item>
      ))}
    </SegmentGroup.Root>
  )
}```

Let's see if @segunadebayo has another idea
