### ISSUE TITLE
[ Menu ] Checking/unchecking an item with keyboard closes the menu, even if closeOnSelect is set to false

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/ark#2147]
### Description

When the closeOnSelect prop is set to false and I select it with the mouse, it doesn't close the menu (as expected)
However, if I select it with keyboard, it closes the menu (unexpected)

### Link to Reproduction (or Detailed Explanation)

https://github.com/FilipePfluck/PlucoUI

### Steps to Reproduce

1. Clone the repo
2. Run storybook
3. Go to the menu Story

### Ark UI Version

1.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@FilipePfluck 

Thanks for taking your time to report this issue. This was fixed in the latest release (see attachment) 
For the next issue please use this [template](https://codesandbox.io/p/devbox/ark-ui-react-issue-template-7hspkh) to create a CodeSandbox. 

https://github.com/chakra-ui/ark/assets/1846056/a1b87791-ecf8-45e9-91df-f1b65444525f
