### ISSUE TITLE
Aria role does not exist in Toast

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#2292]
### Description

![image](https://github.com/chakra-ui/ark/assets/53458125/5b4ed4dc-5ec3-4387-8202-757fd51db976)

### Link to Reproduction (or Detailed Explanation)

https://pagespeed.web.dev/analysis/https-ark-ui-com-docs-components-toast/k4at8ulapm?form_factor=desktop

### Steps to Reproduce

Put a Toaster in your application and test page speed

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
This feels odd. The aria role of region is a valid value, not sure why the page speed insight considers it incorrect.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/region_role

We tested this against a few screen readers before landing in this role. There’s nothing we can do here

**Comment by mupinnn** [comment]
@segunadebayo I think because the Lighthouse is using this spec https://www.w3.org/TR/html-aria/#el-ul to check which `role` attribute is allowed to be used with an element.

The newer version of Ark UI will not get this error since the toast group element switched to `div`, but the older version does (https://github.com/chakra-ui/ark/blob/%40ark-ui/vue%400.11.0/packages/frameworks/vue/src/toast/toast-group.tsx), and there is no way to change the toast group element via props? The only way is to update the package @juliomuhlbauer
