### ISSUE TITLE
Closing Nested Child Dialog Also Closes Parent Dialog/Popover on Touch Screen

### ISSUE THREAD

**Issue by elson-currentcorp** [chakra-ui/ark#2557]
### Description

I have the following UI flow:

Dashboard Button -> Popover -> Parent Dialog -> Child Dialog

I'm encountering a very weird bug where if you close the Child Dialog, it triggers the parent dialog's onOpenChange and closes it as well as the Popover. This bug only happens on a touch screen and only on button elements.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-ivpkst?file=src%2FApp.tsx

### Steps to Reproduce

0. Make sure you are on a touch screen device (etc. developer tools device emulation)
1. Click  "Open Popover" button
2. Click "Open Parent Dialog" button in popover
3. Click "Open Child Dialog" button in parent dialog
4. Click "Close" button in child dialog

The expected behavior is that only the child dialog should close, which takes you back to pre-step 3.

This works perfectly fine on PC using the mouse cursor, but on mobile/touch screen, it bugs. When you click the "Close" button, everything, all dialogs and the popover will close. I have tested this using the developer tools simulator and a physical iPad.

https://github.com/chakra-ui/ark/assets/148154522/85f788bd-a111-4e11-b157-abc5e9e0731b

### Ark UI Version

^3.3.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome, Safari, Edge

### Additional Information
- I believe this bug has been present since Ark V2
- This bug may have something to do with the trapFocus prop
- Bug still occurs even if closeOnInteractOutside is set to false
- Closing the Child Dialog via other means such as ESC or clicking on the backdrop does NOT trigger the bug.
- Using a custom button without the close trigger wrapper (etc `<button onClick={() => setIsOpen(false)}/>`) also triggers the bug.
- Using a custom button and a setTimeout, or onPointerDown instead of onClick does NOT trigger the bug.

**Comment by segunadebayo** [comment]
Hi @elson-currentcorp,

I looked into this and saw that it's caused by the dance between the focus trap, interaction outside, and portals.

It's not exactly a bug, though. Let's go through the logic
- Parent Dialog trigger is clicked: Parent dialog is open and portalled, and focus trap is active
- Child Dialog trigger is clicked: Because child dialog is portalled, it's considered outside of the parent dialog's content, and the focus trap forces focus back to the parent dialog.
- Interaction (or focus) outside: Due to the timings for touch events, it might happen that focus outside is detected by the parent dialog and causes it to close.

**Take this as the general rule of thumb, I will add this to the docs as well:**

When nesting dialogs (with active focus traps), we recommend only portalling the root parent dialog. Every other dialog should be nested within the root dialog.

**In view of this, here's my suggested solution:**

- Removed `Portal` from the child dialog
- Move child dialog within parent dialog
- Add back `trapFocus` to the child dialog (since this is helpful for accessibility)
- (Optional) Remove portalled from popover since its content is not actually portalled

https://stackblitz.com/edit/vitejs-vite-yccjeg?file=src%2FApp.tsx

**Comment by segunadebayo** [comment]
Here's a working solution for the composition
https://github.com/chakra-ui/ark/commit/e5d987422762d988809e457beaa27d931c5df390

**Comment by elson-currentcorp** [comment]
Hi @segunadebayo thanks for getting back to me.

I have a few questions:

1. You said that portalled doesn't do anything on the popover, this is referring to the prop only right? I noticed that the composition example you provided still portals the popover.

2. What happens if there is a use case where I have multiple warning dialogs triggered in sequence? They are not nested in the hierarchical sense, but still overlap each other in any arbitrary order, and all are portalled because they can be triggered globally from anywhere. I would like to be able to close one at a time like a toast component, without the issue described in this post.

3. I am still encountering the issue described in this post in the stackblitz link you posted, closing the child dialog is fine, but closing the parent dialog still automatically closes the popover on touch screen. The composition example you posted works perfectly, however the positioning of the dialog is fixed within the popover (since it is positioned using transforms).

**Comment by elson-currentcorp** [comment]
EDIT: 

I have two potential userland solutions for 3.

1. I set closeOnInteractOutside to false in the popover and implement a custom prop called closeOnClickOutside. This way the popover can still be closed manually by the user when clicking outside, but doesn't close randomly when focus changes on dialog close.

2. Since my dialogs are all controlled, I use the finalFocusEl prop to manually refer to an element in the popover.

**Comment by blended-bram** [comment]
This is still happening; and should be documented in the `Dialog` samples, specifically where you should not use `<Portal>` due to focus trap on parent.
