### ISSUE TITLE
The tooltip will automatically be open if present in a popover

### ISSUE THREAD

**Issue by Piglow19** [chakra-ui/ark#2565]
### Description

When I open the popover containing the button with the tooltip, I expect the tooltip to be closed by default. But instead, both the popover and the tooltip open

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/romantic-torvalds-c8zqwd?workspaceId=8d81aac6-6612-4af0-a377-497f1fe8f106

### Steps to Reproduce

Click on the 'React' tab.
Open the modal by clicking on the '(Popover) Click Me' button.

See? The tooltip is already open! You need to hover your mouse over the 'Hover me' button to close the tooltip...

### Ark UI Version

2.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Opera

**Comment by Piglow19** [comment]
This bug is still present in Ark-UI v3.3.0

**Comment by segunadebayo** [comment]
This is by design, not a bug.

- The popover will autofocus the first focusable element when it opens.
- The tooltip opens when the trigger is focused, hence the reason.

You can fix this by:

- Add a tabIndex to popover title or description
- Add a close button as the first element
- Turning off `autoFocus`
