### ISSUE TITLE
Import not found with moduleResolution set to nodenext

### ISSUE THREAD

**Issue by stellarhoof** [chakra-ui/ark#2953]
### Description

Setting `tsconfig.json`'s `moduleResulution` to `nodenext` causes various imports to not resolve.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/twilight-grass-lygf9y

### Steps to Reproduce

1. Go to provided sandbox
2. Navigate to `src/App.tsx`
3. Verify that the imported type `PolymorphicProps` cannot be resolved.

### Ark UI Version

4.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Brave

**Comment by cschroeter** [comment]
@stellarhoof

Please use `"moduleResolution": "bundler"`
This setting is tailored for use with bundlers like Vite, Webpack, and similar tools.

**Comment by stellarhoof** [comment]
A library should make no assumption on the technology used by consumers. For example I have a dedicated package just for styling ark components which publishes the emitted typescript files and have no need for bundling.

Also, the bug is present even if a bundler is used because this is about TypeScript not being able to resolve the imports.

**Comment by cschroeter** [comment]
Thanks for the detailed explanation. Feel free to file a PR if you have a concrete solution in mind

**Comment by kevva** [comment]
> if you have a concrete solution in mind

Just write `import` statements with `.js` extension in your source like the example above instead of omitting them altogether. This is also inline with how ESM works nowadays. You can read more about it [here](https://nodejs.org/api/esm.html#mandatory-file-extensions). I agree with @stellarhoof that a library shouldn't force workarounds upon its consumers. `panda` had a similar issue which was fixed in [this PR](https://github.com/chakra-ui/panda/pull/1271).
