### ISSUE TITLE
[Tabs] [Vue]: some kebab-case props not working

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#876]
### Description

I noticed some props aren't working when they're kebab cased. It seems to be mostly ones binding an event. Of course this is easily fixed by switching those particular ones to camelCase, but considering autocomplete usually is kebab-cased and the vue style guide strongly recommends kebab in the template, it would be nice if this worked as expected.

I thought it might be a Vue issue, but I found a similar issue on the PrimeVue repo and the relevant PR that solved their issue.

https://github.com/primefaces/primevue/issues/1263

From the PR:

>This is hopefully resolved now, components with issues were DataTable and TreeTable mainly who need to access their >children. Since Vue 3 remove $children with no replacement, we had to use vnodes that caused this as we use camel by >default. Just like Vue does, we now do kebab-camel conversion for these components and the issue is resolved. If one >day $children is back, we'll migrate to that for sure. Thanks for everyone contributed to this issue. 4th of October is the >release for 3.7.3

So perhaps doing a similar prop name conversion might work here?

P.S. I titled this under the Tabs component but if I remember correctly, I was having this issue with others as well.

### Link to Reproduction

https://stackblitz.com/edit/nuxt-starter-3jzcrb?file=components%2FCustomTabsComponent.vue

### Steps to reproduce

notice the `:on-change` prop function doesn't run as is. Changing to `:onChange` on the `Tabs` component allows the function to run.

### Ark UI Version

0.2

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

112.0.5615.165

**Comment by Shyrro** [comment]
Hey @jiblett1000 

Thanks for filing this. Actually for the events, they should be written the Vue way instead of binding them as props. 
Maybe we should document this, but instead of doing `:onChange` you should actually write `@change`.
For example, in the Tabs components you can use `@change`, `@focus` and `@delete`.

In the docs, if you select the Vue framework, you have some code snippets that use the right Vue syntax : https://ark-ui.com/docs/vue/components/tabs

I'm actually even surprised that `:onChange` even works, i'll check this.

**Comment by jiblett1000** [comment]
@Shyrro Ah, ok. Autocomplete strikes again. Thank :)

Just FYI; these seem to work as well `@onChange`, `@on-change`.

Yeah, I don't think I've noticed any regular props not working with kebab either.

**Comment by jiblett1000** [comment]
@Shyrro I take that back. Only `@change` is working. Not `@onChange` or `@on-change`
