### ISSUE TITLE
[Solid]: buttons inside tooltip triggers become un-clickable

### ISSUE THREAD

**Issue by Drummss** [chakra-ui/ark#908]
### Description

When I use a button inside of a tooltip trigger I expect the button to still be clickable.

### Link to Reproduction

https://codesandbox.io/p/sandbox/happy-night-t0rptz?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

See the provided codesandbox link and click on the provided buttons. You will see that the counter increases with no tooltip but does not increase with a tooltip attached.

### Ark UI Version

0.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Firefox 112.0.2

**Comment by RagOfJoes** [comment]
Based on [zag's documentation](https://zagjs.com/components/solid/tooltip#pointerdown-behavior) this seems to be the expected behavior when `closeOnPointerDown` is either not provided or set to `true`. However, even if you set `closeOnPointerDown={false}` the tooltip still closes and hijacks the `onClick` event from the button.

Quick workaround that I found was just wrapping the `button` with a `div` or a `span`.

**Comment by Drummss** [comment]
I appreciate you looking into this for me, and thank you for the quick workaround suggestion!

Although this is programmed behavior would it still be considered to be undesired behavior? It makes more sense - to me at least - for any event that is hijacked by the tooltip to still be dispatched to the element it is wrapping.

Any thoughts on that?

**Comment by cschroeter** [comment]
Thanks for taking time to report this issue. This should work as you've described and I'm happy to report that with the upcoming https://github.com/chakra-ui/ark/pull/896 the following should be just fine.

```tsx
<TooltipTrigger onClick={incrementCount}>Tooltip</TooltipTrigger>

// or with new `asChild` syntax

<TooltipTrigger asChild>
  <button onClick={incrementCount}>Tooltip</button>
</TooltipTrigger>
```
