### ISSUE TITLE
Improve support for recently released `defineProps` in Vue.

### ISSUE THREAD

**Issue by Shyrro** [chakra-ui/ark#978]
```ts
import type { NumberInputProps } from "@ark-ui/vue";

interface Props {
  label: string;
  id?: string;
  paddingRight?: number;
  paddingLeft?: number;
}

const props = defineProps<NumberInputProps & Props>();
```

Vue now supports passing types to the `defineProps` method since Vue 3.3. 
However, with Ark types this shows different errors for some reason. 

https://stackblitz.com/edit/nuxt-starter-3jzcrb?file=components%2FChildDialog.vue

_Originally posted by @jiblett1000 in https://github.com/chakra-ui/ark/issues/918#issuecomment-1550347164_

NB: this might be coming from the polymorphic factory types and might be solved by migrating to the `asChild` prop.

**Comment by jiblett1000** [comment]
@Shyrro Thanks for this :smile:

**Comment by cschroeter** [comment]
Unfortuantely it turned out that this is not possbile due to intenstive use of generics in zag.js

Instead I wrote a script that turns a typescript interface into vue props. https://github.com/chakra-ui/ark/blob/main/scripts/src/generate-vue-props.ts

We going to use this auto generated props / emits instead.
